[package]
name = "agile_bus_mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
rumqttc = "0.16"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "time", "sync", "macros"] }
agile_common = { path = "../common" }

[dev-dependencies]
pretty_assertions = "1.4"
